# Generated by Django 3.0.3 on 2020-12-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealingBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('keyword', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=1000)),
            ],
        ),
    ]
