# Generated by Django 3.0.3 on 2020-12-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLovers', '0002_auto_20201211_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healingbook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='healingbook',
            name='image',
        ),
        migrations.RemoveField(
            model_name='healingbook',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='healingbook',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='healingbook',
            name='review',
        ),
        migrations.RemoveField(
            model_name='healingbook',
            name='title',
        ),
        migrations.AlterField(
            model_name='healingbook',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
