# Generated by Django 3.0.3 on 2020-12-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLovers', '0004_auto_20201214_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn13', models.IntegerField(default=0)),
                ('addition_symbol', models.IntegerField(default=0)),
                ('class_no', models.FloatField(default=0)),
            ],
        ),
    ]
