# Generated by Django 3.0.3 on 2020-12-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLovers', '0006_auto_20201215_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybook',
            name='isbn13',
            field=models.TextField(default=''),
        ),
    ]
