# Generated by Django 3.0.3 on 2020-12-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLovers', '0008_auto_20201215_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultBook',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.TextField(default='')),
                ('author', models.TextField(default='')),
                ('publisher', models.TextField(default='')),
                ('publication_year', models.TextField(default='')),
                ('isbn13', models.TextField(default='')),
                ('addition_symbol', models.TextField(default='')),
                ('vol', models.TextField(default='')),
                ('class_no', models.TextField(default='')),
                ('loan_count', models.IntegerField(default=0)),
                ('bookImageURL', models.TextField(default='')),
                ('keyword', models.TextField(default='')),
                ('describe', models.TextField(default='')),
                ('intro', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ChildBook',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.TextField(default='')),
                ('author', models.TextField(default='')),
                ('publisher', models.TextField(default='')),
                ('publication_year', models.TextField(default='')),
                ('isbn13', models.TextField(default='')),
                ('addition_symbol', models.TextField(default='')),
                ('vol', models.TextField(default='')),
                ('class_no', models.TextField(default='')),
                ('loan_count', models.IntegerField(default=0)),
                ('bookImageURL', models.TextField(default='')),
                ('keyword', models.TextField(default='')),
                ('describe', models.TextField(default='')),
                ('intro', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TeenagerBook',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.TextField(default='')),
                ('author', models.TextField(default='')),
                ('publisher', models.TextField(default='')),
                ('publication_year', models.TextField(default='')),
                ('isbn13', models.TextField(default='')),
                ('addition_symbol', models.TextField(default='')),
                ('vol', models.TextField(default='')),
                ('class_no', models.TextField(default='')),
                ('loan_count', models.IntegerField(default=0)),
                ('bookImageURL', models.TextField(default='')),
                ('keyword', models.TextField(default='')),
                ('describe', models.TextField(default='')),
            ],
        ),
    ]
